---
title: "TakeHomeTest - Kalon Goonetilleke"
author: "Kalon Goonetilleke"
date: "12/8/2021"
output: html_document
---


```{r ggp1, echo=FALSE}
plot(ggp1)
```
<b> <center> #SetUp for The Code </b> </center>
#I called the following libraries as below
```
getwd()

library("gridExtra") 
library("readxl")
library("tidyverse")
library("dplyr")
library("ggplot2")
library("lubridate")
library("rtsplot")
library("xts")
```

#I read in the Excel File and assigned it to a dataframe. We have 174,226 rows
```
df <- read_excel("/Users/kalong/Desktop/CODE3/dataset.xlsx")
df
tidy_names(df)
```
#I converted creative_name to creative_name_low in Excel. 
#I proceeded to select creative name lowercase and assign it to creativedf
```
creativedf <- select(df, creative_name_low)
#verifying my method
creativedf
```  
<center><b> #Question 1 </b> </center>
#How many versions of creative were run?
#There were 10 versions of creative run. They are black, blacknew, grey, grey new,
#orange, orange new, teal, teal new, white, and white new. 
```
creativedf %>%
  group_by(creative_name_low) %>%
  summarise( n = n())
count(unique(creativedf))
```

#Assigning creative_name to creative

<center> <b>#Question 2 </b> </center>
<b>
# Did the newer version of creative have any effect? If so, how much? </b>

#What I did here was create a dataframe (newcre) that only has new creatives
#I wanted to see the impact of impressions, clicks, and conversions for old vs. new creatives
```
ndf <- select(df, creative_name_low, impressions, clicks, conversions)
ndf

newcre <- ndf %>% filter(grepl('new', creative_name_low))
newcre
#Extract data I want
newcreatives <- select(newcre, creative_name_low, impressions, clicks, conversions)
```

#I created a data frame that has standard creatives(exclusive of new ones)
#I called it 'stdcre'
```
#Create a dataframe that has 'standard' creatives
stdcre <- ndf %>% filter(!grepl('new', creative_name_low))
#Extract Data I want
stdcreatives <- select(stdcre, creative_name_low, impressions, clicks, conversions)
```


#Verifying my results to see if they are separated
```
head(newcreatives)

head(stdcreatives)
```

#I compared clicks between new and old
```
ggp1 <- ggplot(stdcreatives, aes(x = factor(creative_name_low), y = clicks)) + 
  geom_bar(stat = "summary", fun = "mean")
```

```{}
plot(ggp1)
```

ggp2<- ggplot(newcreatives, aes(x = factor(creative_name_low), y = clicks)) + 
  geom_bar(stat = "summary", fun = "mean")

ggp1
ggp2
grid.arrange(ggp1, ggp2, ncol=2)
```

###
#I compared impressions between new and old
par(mfrow=c(2,1))
```
ggp3 <- ggplot(stdcreatives, aes(x = factor(creative_name_low), y = impressions)) + 
  geom_bar(stat = "summary", fun = "mean")

ggp4<- ggplot(newcreatives, aes(x = factor(creative_name_low), y = impressions)) + 
  geom_bar(stat = "summary", fun = "mean")

ggp3
ggp4
grid.arrange(ggp3, ggp4, ncol=2)
```


###
#I compared conversions between new and old
par(mfrow=c(2,1))
ggp5 <- ggplot(stdcreatives, aes(x = factor(creative_name_low), y = conversions)) + 
  geom_bar(stat = "summary", fun = "mean")

ggp6<- ggplot(newcreatives, aes(x = factor(creative_name_low), y = conversions)) + 
  geom_bar(stat = "summary", fun = "mean")

ggp5
ggp6
grid.arrange(ggp5, ggp6, ncol=2)

<center> <b>#Question 3 </b> </center>
#<b> Show the CPA and CVR for each campaign type that was run. </b>
#I defined CPA to be cost per acquisition
#Where CPA is total amount spent / total attributed conversions

q3df <- select(df, campaign_name, creative_name_low, month, spend, impressions, clicks, conversions)
head(q3df)

spend <- q3df %>%
  group_by(campaign_name) %>%
  summarise( sumspend = sum(spend))

sumofconv<- q3df %>%
  group_by(campaign_name) %>%
  summarise(sumconversion = sum(conversions))

total <- merge(sumofconv, spend)
head(total)

total$CPA <- (total$sumspend / total$sumconversion)
tail(total)
#Printing and checking whether CPA is printing as a new column for each campaign

#I defined CVR to be the conversion rate
#where the users saw ad and took action as a result
#CVR is (number of conversions/number of impressions ) * 100
q3df
q3df$CVR <- ((q3df$conversions / q3df$impressions) * 100)
head(q3df)

<center><b> #Question 4 </b> </center>

<b> #Which campaign type was more efficient at driving conversions? By how much? </b>
#To find this, I plotted a graph of conversions relative to campaign type

##In order to sort by campaign type, I had to create different groups
##For example, I created and filtered by branding, conversions and fan acquisitions
#Filtered by branding, conversions, fanacquistions

q4df<- select(df, campaign_name, conversions)
head(q4df)
tail(q4df)
```
campbrand <- q4df %>% filter(grepl('branding', campaign_name))
campconver <- q4df %>% filter(grepl('conversions', campaign_name))
campfana <- q4df %>% filter(grepl('fanacquisition', campaign_name))

campbrand
campconver
campfana

campbrandsum<- campbrand %>%
  summarise(sumbrandconversion = sum(conversions))
campbrandsum

campconversum<- campconver %>%
  summarise(sumconverconver = sum(conversions))
campconversum

campfanasum<- campfana %>%
  summarise(sumcampfanasum = sum(conversions))
campfanasum
```
#These are the total sum of the conversions, based 
#on the respective types of campaigns run
```
campfanasum
campconversum
campbrandsum
```

##I carried out carried out basic statistics for comparisons
```
summary(campconver)
summary(campfana)
summary(campbrand)
```

plot(q4df$campaign_name, q4df$conversions)
qplot(campaign_name, conversions, data=q4df)

##Here we can see that some campaigns have a
#significantly more effective conversion rate than others.
sumofconv<- q4df %>%
  group_by(campaign_name) %>%
  summarise(sumconversion = sum(conversions))

head(sumofconv)

ggp7 <- ggplot(sumofconv, aes(x = factor(campaign_name), y = sumconversion)) + 
  geom_bar(stat = "summary", fun = "mean")

ggp7

#Here we can see that by grouping we 
#can obtain a more significant overall picture using mean
##
ggp7
####

<center> <b> #Question 5 </b> </center>
#Are there any time period trends? If so within which metrics and what dimension are they sensitive to?
##Assign months to different time periods
##What metrics/dimensions are time periods sensitive to?
#Time series analysis using R programming
q5df <- select(q3df, month, creative_name_low, spend, impressions, clicks, conversions, CVR)
##Ordering months for q5df

latestdf <- q5df %>%
  arrange(match(month_name, month.name))
head(latestdf)
ggplot(latestdf,aes(x=month_name, y=spend))+geom_line()

monthname <- df$month
monthname
monthnamedf <- month.name[monthname]

head(monthnamedf)
head(months)

options(stringsAsFactors = FALSE)
head(q5df)

q5df <-  q5df %>%
  add_column(month_name = monthnamedf)

##We want to verify that month_name prints the respective month_name
#For each month
str(q5df)

<b> #Part 1 </b>
#Calculating a time series forecast for month_name & spend
ts1 <- select(q5df, month_name, spend)

ts1months <- group_by(ts1) %>%
  group_by(month_name) %>%
  summarise( total_spend = mean(spend))

##Arranging by month name
ts1montharranged <- ts1months %>%
  arrange(match(month_name, month.name))
str(ts1montharranged)  
#Basic bar plot for mean of spend
barplot(ts1montharranged$total_spend,names.arg=ts1montharranged$month_name,xlab="Month",ylab="Mean Spend",col="blue",
        main="Mean Spend per month chart",border="black")

<b> #Part 2 </b>
#Calculating a time series forecast for month_name & impressions
ts2 <- select(q5df, month_name, impressions)
head(q5df)

ggplot(q5df,aes(x=month_name, y=impressions))+geom_line()

##Calculating for sum 
ts2months <- group_by(ts2) %>%
  group_by(month_name) %>%
  summarise(mean_impressions = mean(impressions))
##Arranging by month name

ts2montharranged <- ts2months %>%
  arrange(match(month_name, month.name))

barplot(ts2montharranged$mean_impressions,names.arg=ts2montharranged$month_name,xlab="Month",ylab="Mean Impressions",col="blue",
        main="Mean Impressions per month chart",border="black")

<b> ##Part 3 </b>
#Calculating a time series forecast for month_name & clicks
ts3 <- select(q5df, month_name, clicks)
ts3

ggplot(q5df,aes(x=month_name, y=clicks))+geom_line()
##Stays relatively the same

ts3months <- group_by(ts3) %>%
  group_by(month_name) %>%
  summarise( mean_clicks = mean(clicks))

##Arranging by month name
ts3montharranged <- ts3months %>%
  arrange(match(month_name, month.name))

barplot(ts3montharranged$mean_clicks,names.arg=ts3montharranged$month_name
        ,xlab="Month",ylab="Mean Clicks",col="blue",
        main="Mean Clicks per month chart",border="black")


<b> #Part 4 </b>
#Calculating a time series forecast for month_name & conversions
ts4 <- select(q5df, month_name, conversions)
ts4
ggplot(q5df,aes(x=month_name, y=conversions))+geom_line()

##Stays relatively the same

##Looking at averages to compare using bar graphs
ts4months <- group_by(ts4) %>%
  group_by(month_name) %>%
  summarise( mean_conversions = mean(conversions))

##Arranging by month name
ts4montharranged <- ts4months %>%
  arrange(match(month_name, month.name))

barplot(ts4montharranged$mean_conversions,names.arg=ts4montharranged$month_name,
        xlab="Month",ylab="Mean Conversions",col="blue",
        main="Mean Conversions per month chart",border="black")

<b> #Part 5 </b>
#Calculating a time series forecast for month_name & CVR
ts5 <- select(q5df, month_name, CVR)
ts5

ggplot(q5df,aes(x=month_name, y=CVR))+geom_line()

##Rather drastic swings in month to month
ts5months <- group_by(ts5) %>%
  group_by(month_name) %>%
  summarise( mean_CVR = mean(CVR))

##Arranging by month name
ts5montharranged <- ts5months %>%
  arrange(match(month_name, month.name))

barplot(ts5montharranged$mean_CVR,names.arg=ts5montharranged$month_name,
        xlab="Month",ylab="Mean CVR",col="blue",
        main="Mean CVR per month chart",border="black")

<center> <b> #Question 6 </b> </center>
#How many creative colors were run in February?
Using this, I was able to find the 
```
q6df <- select(q5df, month_name, creative_name_low)
tail(q6df)

q6df %>%
  group_by(month_name = "February" = TRUE) %>%
  summarise(q6df)
```


<b> <center> #Question 7 </b> </center>
#If this client asked you what CPA you'd project for next month 
#what would be the most important questions you want to ask prior 
#to providing a response?



